# Generated by Django 3.2.19 on 2023-06-25 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('layer', '0009_alter_layer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id_form', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unnamed Form', max_length=3000)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layer.layer')),
            ],
            options={
                'db_table': 'maps_layers_forms',
                'ordering': ['pk'],
                'managed': True,
            },
        ),
    ]
