# Generated by Django 3.2.19 on 2024-10-27 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layer', '0014_alter_layer_layer_type'),
        ('form', '0002_auto_20230625_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='layer.layer'),
        ),
    ]
