# Generated by Django 3.2.19 on 2023-06-24 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_rename_map_maps'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maps',
            options={'managed': True, 'ordering': ['pk']},
        ),
        migrations.AlterModelTable(
            name='maps',
            table='maps',
        ),
    ]
