# Generated by Django 3.2.19 on 2023-06-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_alter_map_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='map',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
