# Generated by Django 3.2.19 on 2023-06-24 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('layer', '0004_rename_geometry_type_layer_layer_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geometry',
            fields=[
                ('id_geometry', models.AutoField(primary_key=True, serialize=False)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layer.layer')),
            ],
            options={
                'db_table': 'maps_layers_geometrys',
                'ordering': ['pk'],
                'managed': True,
            },
        ),
    ]
