# Generated by Django 3.2.19 on 2023-06-24 13:28

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geometry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geometry',
            options={'managed': True, 'ordering': ['pk'], 'verbose_name_plural': 'Geometries'},
        ),
        migrations.AddField(
            model_name='geometry',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326),
        ),
    ]
