# Generated by Django 3.2.19 on 2023-06-24 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geometry', '0002_auto_20230624_1328'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='geometry',
            table='maps_layers_geometries',
        ),
    ]
