# Generated by Django 3.2.19 on 2023-06-24 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('map', '0004_rename_maps_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id_layer', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=3000, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.map')),
            ],
            options={
                'db_table': 'layers_maps',
                'ordering': ['pk'],
                'managed': True,
            },
        ),
    ]
