# Generated by Django 3.2.19 on 2023-06-24 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='layer',
            table='maps_layers',
        ),
    ]
