# Generated by Django 3.2.19 on 2023-06-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layer', '0002_alter_layer_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='geometry_type',
            field=models.CharField(choices=[('PL', 'POLYGON'), ('PO', 'POINT'), ('LN', 'LINE'), ('GE', 'GEOMETRY')], default='GE', max_length=2),
        ),
    ]
