# Generated by Django 3.2.19 on 2023-06-24 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layer', '0003_layer_geometry_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='layer',
            old_name='geometry_type',
            new_name='layer_type',
        ),
    ]
