# Generated by Django 3.2.19 on 2023-06-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layer', '0004_rename_geometry_type_layer_layer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
