# Generated by Django 3.2.19 on 2023-06-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layer', '0006_alter_layer_layer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='layer_type',
            field=models.CharField(choices=[('POLYGON', 'POLYGON'), ('POINT', 'POINT'), ('LINESTRING', 'LINESTRING'), ('GEOM', 'GEOMETRY')], default='GEOM', max_length=10),
        ),
    ]
