# Generated by Django 3.2.19 on 2023-06-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layer', '0008_alter_layer_layer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='name',
            field=models.CharField(default='Unnamed Layer', max_length=3000),
        ),
    ]
