# Generated by Django 3.2.19 on 2024-06-21 23:05

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layer', '0009_alter_layer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='style',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
