# Generated by Django 3.2.19 on 2024-06-21 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layer', '0010_layer_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='style',
            field=models.JSONField(default=dict),
        ),
    ]
