# Generated by Django 3.2.19 on 2024-06-22 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layer', '0011_alter_layer_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='layer_type',
            field=models.CharField(choices=[('POLYGON', 'POLYGON'), ('POINT', 'POINT'), ('LINESTRING', 'LINESTRING'), ('MULTIPOLYGON', 'MULTIPOLYGON'), ('MULTILINESTRING', 'MULTILINESTRING'), ('GEOM', 'GEOMETRY')], default='GEOM', max_length=15),
        ),
    ]
