# Generated by Django 3.2.19 on 2024-06-23 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layer', '0012_alter_layer_layer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
