# Generated by Django 3.2.19 on 2023-06-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('value', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='value',
            old_name='varchar_value',
            new_name='string_value',
        ),
        migrations.AddField(
            model_name='value',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='value',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
