# Generated by Django 3.2.19 on 2023-06-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='type',
            field=models.CharField(choices=[('NUMBER', 'NUMBER'), ('STRING', 'STRING')], default='STRING', max_length=6),
        ),
    ]
