# Generated by Django 3.2.19 on 2024-06-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0003_auto_20230625_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='type',
            field=models.CharField(choices=[('Number', 'Number'), ('String', 'String')], default='String', max_length=6),
        ),
    ]
