# Generated by Django 3.2.19 on 2024-06-23 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0004_alter_field_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field',
            old_name='id_form',
            new_name='id_field',
        ),
    ]
