# Generated by Django 3.2.19 on 2024-10-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0005_rename_id_form_field_id_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(default='Unnamed Field', max_length=3000),
        ),
    ]
